$background = 2e3440         # Nord0
$surface = 4c566a            # Nord3
$surface_bright = d8dee9     # Nord4
$foreground = 4c566a         # Nord6
$accent = 88c0d0             # Nord8
$red = bf616a                # Nord11
$orange = d08770             # Nord12
$yellow = ebcb8b             # Nord13
$green = a3be8c              # Nord14
$blue = 5e81ac               # Nord9
$shadow = 4c566a             # Nord10
