# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

windowrule = suppress_event maximize, match:class .*0windowrulev2=nofocus, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = opacity 0.0 override, no_anim on, no_initial_focus on, max_size 1 1, no_blur on, no_focus on, match:class ^(xwaylandvideobridge)$

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = immediate 1, match:class ^(FreeCAD)$