# Look and Feel
source = ~/.config/hypr/config/UI/animation.conf
source = ~/.config/hypr/config/UI/decoration.conf
source = ~/.config/hypr/config/UI/layout.conf
source = ~/.config/hypr/config/UI/windowRule.conf

# Monitors
source = ~/.config/hypr/config/monitor/monitorBind.conf
source = ~/.config/hypr/config/monitor/monitorPC.conf
source = ~/.config/hypr/config/monitor/workspacesPC.conf
# source = ~/.config/hypr/config/monitor/monitorLaptop.conf
# source = ~/.config/hypr/config/monitor/workspacesLaptop.conf

# System
source = ~/.config/hypr/config/system/environment.conf
source = ~/.config/hypr/config/system/bind.conf
source = ~/.config/hypr/config/system/execStartup.conf
source = ~/.config/hypr/config/system/input.conf
source = ~/.config/hypr/config/system/misc.conf








