$mpris_art = /tmp/hyde-mpris.png
$wall = $HOME/.config/hypr/wallpaper/current

# BACKGROUND
background {
    monitor = 
    path = $wall
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.1
}

# GENERAL
general {
    no_fade_in = false
    disable_loading_bar = true
    grace = 0
}

# Time
label {
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%X")</span>"
    color = rgb(205, 214, 244)
    font_size = 50
    text_align = right
    position = -30, 70
    halign = right
    valign = bottom
}

# Day-Month-Date
label {
    monitor = 
    text = cmd[update:1000000] echo "<span>$(date "+%A, %d %B %Y")</span>"
    color = rgb(205, 214, 224)
    font_size = 20
    text_align = right
    position = -30, 30
    halign = right
    valign = bottom
}

# User info
shape {
    monitor = 
    size = 1000, 500
    color = rgba(29, 31, 40, 0.85)
    rounding = 20
    rotate = 0
    position = 0, -150
    halign = center
    valign = center
}

# Profie-Photo
#image {
#    monitor = 
#    path = ~/img/avatar/ava_new_year2.jpg
#    border_size = 0
#    border_color = rgba(29, 31, 40, 0.75)
#    size = 300
#    rounding = -1
#    rotate = 0
#    reload_time = -1
#    reload_cmd =
#    position = 0, 150
#    halign = center
#    valign = center
#}

# GREETINGS
label {
    monitor = 
    text = Hi, $USER
    color = rgb(205, 214, 244)
    font_size = 60
    position = 0, -50
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor = 
    size = 420, 75
    outline_thickness = 3
    rounding = 10
    dots_size = 0.1 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.3 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(192, 202, 245, 0.3)
    inner_color = rgba(29, 31, 40, 0.5)
    font_color = rgb(192, 202, 245)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##bac2de">password...</span></i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

image {
  monitor = 
  size = 60
  border_size = 0
  path = ~/.config/hypr/img/poweroff.png
  onclick = poweroff
  position = 40, -300
  halign = center
  valign = center
}

image {
  monitor = 
  size = 60
  border_size = 0
  path = ~/.config/hypr/img/restart.png
  onclick = reboot
  position = -40, -300
  halign = center
  valign = center
}

# Music blur div
shape {
    monitor = 
    size = 500, 140
    color = rgba(29, 31, 40, 0.7)
    rounding = 20
    position = 0, -10
    halign = center
    valign = top
    zindex = 1
}

# Music Album Art
#image {
#    monitor = DP-1
#    path = 
#    size = 100
#	  border_size = 0
#	  border_color = rgba(255, 255, 255, 0.8)
#    rounding = 5
#    rotate = 0
#    reload_time = 1
#    reload_cmd = echo "$(playerctl metadata | grep 'mpris:artUrl' | awk '{print $3}')" 
#    position = 40, -30
#    halign = left
#    valign = top
#    zindex = 1
#}

# PLAYER TITLE
label {
    monitor =
    text = cmd[update:500] playerctl metadata xesam:title
    color = rgb(205, 214, 244)
    font_size = 20
    text_align = center
    position = 0, -30
    halign = center
    valign = top
    zindex = 1
}

# PLAYER ARTIST
label {
    monitor = 
    text = cmd[update:500] playerctl metadata xesam:artist
    color = rgb(186, 194, 222)
    font_size = 15
    text_align = center
    position = 0, -65
    halign = center
    valign = top
    zindex = 1
}


# PLAYER LENGTH
label {
    monitor = 
    text = cmd[update:100] playerctl metadata mpris:length | awk '{ms=$1/1000000; min=int(ms/60); sec=int(ms%60); printf "%d:%02d\n", min, sec}'
    color = rgb(205, 214, 244)
    font_size = 15
    text_align = center
    position = 0, -110
    halign = center
    valign = top
    zindex = 1
}

