# Cursor
env = HYPRCURSOR_THEME,Nordzy-hyprcursors
env = no_hardware_cursors,1
env = HYPRCURSOR_SIZE,30
env = XCURSOR_THEME,Nordzy-cursors
env = XCURSOR_SIZE,30
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Nordzy-cursors'

# General Hyprland
env = HYPRLAND_NO_SD_NOTIFY,1
env = HYPRSHOT_DIR,$HOME/Pictures/Hyprshot

#QT theme
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORM,wayland;# hyprland.conf
env = QT_QPA_PLATFORMTHEME,qt6ct

# Nvidia specific 
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,0
env = __GL_GSYNC_ALLOWED,1
env = LIBVA_DRIVER_NAME,nvidia

# For GTK3/4 themes (replace with your theme name)
env = GDK_BACKEND,wayland,x11
env = GTK_THEME,Nordic-darker
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# XDG
env = XDG_CURRENT_DESKTOP="Hyprland";
env = XDG_SESSION_TYPE="wayland";
env = XDG_SESSION_DESKTOP="Hyprland";

# Japanese
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx


# Permission
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/discord, screencopy, allow
permission = /usr/(bin|local/bin)/steam, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow


opengl {
  nvidia_anti_flicker = true
}

ecosystem {
  no_update_news = true
  no_donation_nag = true
}