misc {
  force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
  disable_scale_notification = true
  font_family = Monaspace Krypton Frozen
  vfr = true
  vrr = 2
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
  animate_manual_resizes = false
}